name: 'RelayDispatch Setup QEMU'
description: 'Configures QEMU emulator support for multi-platform container builds'
inputs:
  platforms:
    description: 'QEMU emulator platforms'
    required: false
    default: 'all'
runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      with:
        platforms: ${{ inputs.platforms }}
